import Script from 'next/script';

import { Header } from 'components';
import { CustomProvider } from 'redux';

import '../styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <CustomProvider>
      <html lang="en">
        <Script src="https://kit.fontawesome.com/f0ad28ac2a.js" crossOrigin="anonymous" />
        <body className="purpleTheme">
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </CustomProvider>
  );
}
